<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- We changed this from Exe to WinExe. This hides the black console window! -->
    <OutputType>WinExe</OutputType> 
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>